version: "3.6"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    volumes:
      - "./:/web/"
      - "/web/node_modules"
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://server:4000/}
      BACKEND_URL_WS: ${BACKEND_URL_WS:-ws://server:4000/}
    networks:
      - pi2

networks:
  pi2:
    external: true
